### ISSUE TITLE
Update Config to support Connectors that produce to multiple topics

### ISSUE THREAD

**Issue by nicholastmosher** [infinyon/fluvio-connectors#101]
There are some cases where it is desirable to have a Connector produce to multiple topics at the same time. In these cases, users should be able to specify the names of each topic individually.

For example, with the in-progress GitHub Connector, there are multiple endpoints that we retrieve data from, and we'd like to be able to put each endpoint's data into a unique Fluvio topic. It would be useful to be able to define a Map of endpoints to topic names, like this:

```yaml
version: v1
name: my-github-connector:
topics:
  issues: my-issues-topic
  commits: my-commits-topic
  releases: my-releases-topic
  ...etc
```
