### ISSUE TITLE
Schema validation for a given connector

### ISSUE THREAD

**Issue by simlay** [infinyon/fluvio-connectors#14]
A given connector must have an input's schema that describes it's inputs.
Take for example fluvio's action:
```yaml
name: 'fluvio'
description: 'Installs Fluvio CLI from source with required dependencies (e.g. Helm, Rust) and starts a Local Cluster. Used for developing fluvio.'
inputs:
  spus:  # number of SPUs
    description: 'number of SPUs to create for local cluster'
    required: false
    default: "1"
  cluster-type:
    description: 'Type of cluster (i.e. local or kubernetes)'
    required: true
    default: 'local'
  rust-log:
    description: "Add rust log options (e.g. debug, warn, info)"
    required: false
    default: 'warn'
  version:
    description: "Use a specific version of the fluvio CLI (e.g. latest, 0.6.0)"
    required: false
    # Blank default will use stable
    default: ''
```

We need something like this for syslog and a way to verify it at runtime via some connector metadata.
