### ISSUE TITLE
Support multiple headers in the http connector

### ISSUE THREAD

**Issue by simlay** [infinyon/fluvio-connectors#260]
There's an issue where the yaml squashes multiple items with the same key. This might need to be done in the fluvio repo.

To do this we should extend the connector yaml specification in the `parameters` section to be both values and dictonaries.

Example:
```
paramaters:
  header:
    - auth: foo
    - bas: bar
  url: google.com
```
