### ISSUE TITLE
Support SmartModule user-defined parameters in connector configuration

### ISSUE THREAD

**Issue by bneijt** [infinyon/fluvio-connectors#285]
I would like to be able to pass smart module parameters when configuring a connector, as described in https://www.infinyon.com/blog/2021/12/smartmodule-params/ for consumers.

This is currently not possible and it seems that you can only support default parameters when looking at https://github.com/infinyon/fluvio-connectors/blob/main/rust-connectors/common/src/opt.rs#L234

During the configuration of a connector I'm not able to pass --extra-params like when configuring a consumer with a smart module:
```yaml
version: 0.2.0
name: cat-facts
type: http
topic: cat-facts
direction: source
parameters:
  endpoint: https://fact-apis.herokuapp.com/facts/cat
  interval: 15
  map: petfact-mapper
  extra-params: about=cat
```
fails to produce a working connector, while 
```yaml
version: 0.2.0
name: cat-facts
type: http
topic: cat-facts
direction: source
parameters:
  endpoint: https://fact-apis.herokuapp.com/facts/cat
  interval: 15
  map: petfact-mapper
```
works with default parameters.
