### ISSUE TITLE
Allow specifying headers for HTTP connector

### ISSUE THREAD

**Issue by nicholastmosher** [infinyon/fluvio-connectors#74]
When trying out the http connector, I set the endpoint to `https://api.github.com/repos/infinyon/fluvio` and got the following result:

```
Request forbidden by administrative rules. Please make sure your request has a User-Agent header (http://developer.github.com/v3/#user-agent-required). Check https://developer.github.com for other possible causes.
```

It seems that this API requires a "User-Agent" header, which is probably not uncommon. We might want to add support for including headers in the http requests from the http connector.

For reference, I was using the following configuration:

```yaml
version: v1
name: github-api
type: http
topic: github
create_topic: true
direction: source
parameters:
  endpoint: https://api.github.com/repos/infinyon/fluvio
  interval: 30
```

**Comment by sehz** [comment]
What would suggest a change to config to accommodate this use case?

**Comment by nicholastmosher** [comment]
If possible, I think something like the following would work:

```yaml
version: v1
name: github-api
type: http
topic: github
create_topic: true
direction: source
parameters:
  endpoint: https://api.github.com/repos/infinyon/fluvio
  interval: 30
  headers:
  - name: "User-Agent"
    value: "fluvio-connect-http"
```

In terms of launching a connector with a config that takes a list of arguments, I believe it's possible to do something such as:

```rust
#[derive(Debug, StructOpt)]
struct HttpOpt {
    #[structopt(long)]
    headers: Vec<String>,
}
```

Where this would pick up args in the form of:

```
$ http --header "Key=Value" --header "Key=Value"
```

**Comment by nicholastmosher** [comment]
After looking at this more closely, I think we'd need to make a small adjustment.

In the Opts, we would have the `header: Vec<String>` like I suggested before:

```rust
#[derive(Debug, StructOpt)]
struct HttpOpt {
    #[structopt(long)]
    header: Vec<String>,
}
```

But the config file would look slightly different: instead of having

```yaml
  headers:
  - name: "User-Agent"
    value: "fluvio-connect-http"
```

We would have `headers` just be a list of strings to match the `header: Vec<String>` type, like this:

```yaml
  headers:
  - "User-Agent:fluvio-connect-http"
```

I also discovered that headers use `:` rather than `=`, so in the CLI we would use:

```
$ http --header "Key: Value"
```

Instead of `Key=Value`
